- src/app/actions/members/delete/route.jsx
- src/app/manage/events/[id]/page.jsx
- src/app/manage/members/[id]/page.jsx
- src/app/manage/members/page.jsx
- src/components/events/EventActions.jsx
- src/components/events/EventForm.jsx
- src/components/events/EventsTable.jsx
- src/components/members/MemberActions.jsx
- src/components/members/MemberForm.jsx
- src/components/members/MemberPositions.jsx
- src/components/profile/UserMemberships.jsx
- src/constants/events.jsx
Linked to : https://github.com/Clubs-Council-IIITH/events/pull/6
> Event Flow

- src/app/buzz-schedule/page.jsx
- src/components/buzz.jsx
- src/components/clubs/ClubBox.jsx
> Dileep buzz

- src/app/clubs/[id]/members/page.jsx
- src/app/clubs/[id]/page.jsx
- src/app/events/[id]/page.jsx
- src/app/manage/clubs/[id]/edit/page.jsx
- src/app/manage/clubs/[id]/page.jsx
- src/app/manage/events/[id]/edit/page.jsx
- src/app/manage/events/[id]/page.jsx
- src/app/manage/events/code/[code]/page.jsx
- src/app/manage/members/[id]/edit/page.jsx
- src/app/manage/members/[id]/page.jsx
- src/app/profile/[id]/edit/page.jsx
- src/app/profile/[id]/page.jsx
@Dileepadari Can you please test all the pages with all the changes? And then merge this PR
> Redirect to 404 pages, if a certain [id] is not found, for any part of website (Pages with id in url)

- src/app/actions/users/get/full/route.jsx
- src/app/actions/users/save/phone/route.jsx
- src/app/profile/[id]/page.jsx
- src/components/events/EventForm.jsx
- src/gql/mutations/users.jsx
Linked to backend update PR - https://github.com/Clubs-Council-IIITH/users/pull/5
> Make POC Phone Number Compulsory

- src/app/about/clubs-council/cc-members/page.jsx
- src/app/about/clubs-council/tech-members/page.jsx
- src/app/actions/events/progress/route.jsx
- src/app/manage/events/[id]/approve_cc/page.jsx
- src/components/events/EventActions.jsx
- src/components/events/EventApproveForm.jsx
- src/gql/mutations/events.jsx
Linked to https://github.com/Clubs-Council-IIITH/events/pull/22
> Added CC Approver Functionality - for which new CC Approving Page made

- src/app/manage/events/[id]/copy/page.jsx
- src/app/manage/events/[id]/edit/page.jsx
- src/app/manage/events/[id]/page.jsx
One example of #16.
- If one club somehow has access to the event link of other club, say 
eg: "https://clubs.iiit.ac.in/manage/events/66390ac3bc921208ad20d415/edit"
then the club can view the details and perform edits in the page.
- This is happening because the routing only checks whether the user has "club" role,
and give access accordingly.
- Now the page redirects to 404 if the event's clubid and user's uid doesn't match
> security: prevent unauthorized access of one club's event to other club

- src/components/events/EventForm.jsx
@abhiramtilakiiit Please test if this is working, and merge the PR...
Linked PR:
- https://github.com/Clubs-Council-IIITH/users/pull/11
> If POC Phone Number fails, don't submit the event

- src/app/about/clubs-council/page.jsx
Closes https://github.com/Clubs-Council-IIITH/web/issues/54
> Fix the filtering of roles on the about CC page

- src/app/manage/events/[id]/page.jsx
- src/gql/queries/events.jsx
This PR is linked to the mailing in terms of functionality:
The main focus is to remind the club, or inform them about when an approval, has
taken place.
- Added a new section with approval times, which are visiable to both club and CC.
- Changed the GraphQL schema to add these attributes to the database
- Modified the mutations to update the time accordingly.
> feature: add approval times

- src/app/manage/events/[id]/page.jsx
- src/gql/queries/events.jsx
Linked PR: https://github.com/Clubs-Council-IIITH/events/pull/31
> Added event submission details

- src/app/events/page.jsx
Fixed the ongoing event coming in the upcoming event, and then added separate ongoing events section
Linked PR: https://github.com/Clubs-Council-IIITH/events/pull/39
> Fixed ongoing events filtering in eventsGrid

- package-lock.json
- package.json
- src/app/calendar/page.jsx
- src/components/Calendar.jsx
This branch consists changes corresponding to hover effect in calendar. So that whenever user will hover over calendar events or holidays... then they will get a popup display regarding details.
> Calendar hover

- src/components/events/DataForm.jsx
> date validation removed for admins

- src/components/profile/AccountPopover.jsx
- src/contexts/ModeContext.jsx
Since dark theme didn't look good and also login was not working while website was being opened in iframe mode. So fixed those issues by removing popover in iframe mode.
> Iframe theme handler

- src/app/actions/events/create/route.jsx
- src/app/events/page.jsx
- src/app/manage/events/[id]/copy/page.jsx
- src/app/manage/events/[id]/edit/page.jsx
- src/app/manage/events/[id]/page.jsx
- src/app/manage/events/new/page.jsx
- src/components/clubs/ClubButton.jsx
- src/components/events/EventDetails.jsx
- src/components/events/EventForm.jsx
- src/gql/queries/events.jsx
handled collaborating clubs for any event
> Collab events frontend

- src/components/members/MembersTable.jsx
The current members table doesn't look good with multiple roles and looks a bit clunky
I have changed the height of each row to be auto and also added  a divider between each row
in the <Stack>
> fix members table

- package-lock.json
- package.json
- src/components/FileUpload.jsx
- src/components/clubs/ClubBanner.jsx
- src/components/clubs/ClubCard.jsx
- src/components/clubs/ClubForm.jsx
- src/components/events/EventForm.jsx
- src/components/profile/UserForm.jsx
- src/utils/files.jsx
- Adds a file compression for images with a limit with 0.3 Mb. Resized images will have the
`resized_` prefix.
- Adds a new attribute filename for `uploadFile()`, which allows custom filenames
for members nad clubs.
- Adds a new attribute `shape` to fileUpload component.
- Fixes the aspect ratios in the club banners
> Fix imageupload adds important features like file compression

- src/app/gallery/page.jsx
- src/components/ImageMasonry.jsx
- src/components/ImageModal.jsx
Helps in Google Indexing, as otherwise it treats /gallery and /gallery?img=index as different pages
> Simplify Gallery Images Bugger View, and added loading for images

- src/app/manage/events/[id]/page.jsx
- src/gql/queries/events.jsx
Linked PR: https://github.com/Clubs-Council-IIITH/events/pull/45
> Incorporate student body events direct approval by SLO

- src/components/holidays/HolidaysTable.jsx
> FIx Holidays Table sorting issue (the date field)

- src/components/events/DataForm.jsx
Linked PR: https://github.com/Clubs-Council-IIITH/events/pull/47
> Updated all events option into a dropdown for better understanding & Added Equipment and Additional fields

- src/components/ConfirmDialog.jsx
- src/components/FileUpload.jsx
- src/components/events/EventBudget.jsx
- src/components/events/EventForm.jsx
- src/components/members/MemberForm.jsx
- src/components/members/MemberPositions.jsx
- src/components/users/UserImage.jsx
- Add a word wrap to the description
- Add an error check on submit
> Event Form: add budget description word wrap and error

- src/app/events/[id]/page.jsx
- src/app/layout.jsx
- src/components/events/EventDetails.jsx
- Add an opengraph description, which is the same as the club description
- Add time and location information in the title.
> Opengraph: add description and custom title

- src/middleware.js
@abhiramtilakiiit Please verify that the refactored code preserves all existing logic and functionality without altering or removing any part of the original implementation
> Simplify Middleware file

- src/actions/storagefiles/update/server_action.jsx
- src/components/docs/DocForm.jsx
- src/components/docs/DocItem.jsx
- src/components/docs/DocsList.jsx
- src/gql/mutations/storagefiles.jsx
- src/gql/queries/storagefiles.jsx
- src/utils/formatTime.jsx
Linked PR: https://github.com/Clubs-Council-IIITH/interfaces/pull/15
> Added versioning to CC Static documents

- src/app/layout.jsx
- src/app/profile/[id]/page.jsx
- src/components/ActionPalette.jsx
- src/components/Layout.jsx
- src/components/profile/AccountPopover.jsx
- src/components/profile/UserForm.jsx
- src/components/svg/login.svg
- src/contexts/ModeContext.jsx
- src/utils/files.jsx
- Moved the dark mode button outside the DrawerMenu
- Changed the profilemenu to login button when logged out.
- The profile menu was using Popover which blocks scorllling, now we are using popper instead.
> Profile: put dark mode outside and simplify login

- src/components/clubs/ClubForm.jsx
- src/components/events/EventForm.jsx
- src/components/profile/UserForm.jsx
- src/utils/files.jsx
It fixes the imgae upload logic which came about, haphazard way in the DocsPR.
> imageupload: add the files required

- README.md
- Add information about the directory structure of the project
- Add information about the different technology and theming tools used.
- Run through all the basic funtionalities
- Wrtote about additional features and security enhancements in the project
- https://github.com/Clubs-Council-IIITH/members/pull/14
- https://github.com/Clubs-Council-IIITH/users/pull/20
- https://github.com/Clubs-Council-IIITH/interfaces/pull/18
- https://github.com/Clubs-Council-IIITH/events/pull/57
- https://github.com/Clubs-Council-IIITH/clubs/pull/21
- https://github.com/Clubs-Council-IIITH/files/pull/13
- https://github.com/Clubs-Council-IIITH/auth/pull/8
- https://github.com/Clubs-Council-IIITH/gateway/pull/5
> Add more information about the project in the frontend readme

- src/actions/events/reminder/server_action.jsx
- src/app/manage/events/[id]/page.jsx
- src/components/events/EventActions.jsx
- src/gql/mutations/events.jsx
- Add a new reminder button for CC to trigger mail to SLO
- https://github.com/Clubs-Council-IIITH/events/pull/58
- https://github.com/Clubs-Council-IIITH/auth/pull/9
- https://github.com/Clubs-Council-IIITH/auth-dev/pull/8
- https://github.com/Clubs-Council-IIITH/interfaces/pull/19
> manage events: add reminder button

- src/actions/events/report/edit/server_action.jsx
- src/app/manage/events/[id]/report/edit/page.jsx
- src/app/manage/events/[id]/report/page.jsx
- src/components/events/report/EventReportDetails.jsx
- src/components/events/report/EventReportForm.jsx
- src/gql/mutations/events.jsx
Added report edit access for cc and club of the event, slo cant edit the report
> edit report access given to clubs, cc

- src/app/cc-recruitments/all/[id]/page.jsx
- src/app/cc-recruitments/all/page.jsx
- src/app/cc-recruitments/page.jsx
- src/components/cc-recruitments/CCRecruitmentsTable.jsx
- src/components/cc-recruitments/RecruitmentForm.jsx
- src/components/cc-recruitments/YearSelector.jsx
- src/components/events/EventsFilter.jsx
- src/components/events/EventsGrid.jsx
- src/gql/queries/recruitment.jsx
tested and working for me
related PR [https://github.com/Clubs-Council-IIITH/interfaces/pull/22](https://github.com/Clubs-Council-IIITH/interfaces/pull/22)
> changes to accomodate 2025 cc recuritments done

- src/components/members/DataForm.jsx
Frontend accompaniment for [batch filtering for UG and PG while downloading members' data](https://github.com/Clubs-Council-IIITH/members/pull/16)
> Added filtering for ug and pg batches

- src/app/manage/events/[id]/page.jsx
- src/components/events/EventForm.jsx
- src/gql/queries/events.jsx
Added an optional alternate venue dropdown in events/create and events/edit
[Events PR](https://github.com/Clubs-Council-IIITH/events/pull/64)
> Alternate Venue dropdown when creating a new event

- src/app/manage/events/[id]/approve_cc/page.jsx
- src/app/manage/events/[id]/page.jsx
- src/components/events/EventActionTabs.jsx
- src/components/events/EventsGrid.jsx
- src/gql/queries/events.jsx
Incorporates new and optimised logic to fetch clashing events only, instead of all the events. 
Clashing location feature should work fine with this.
> Reduce clashing events query 

- src/app/manage/holidays/page.jsx
- src/components/holidays/HolidaysTable.jsx
- src/components/holidays/HolidaysToggleBar.jsx
- src/components/holidays/ManageHolidaysClient.jsx
> toggle to filter past holidays in manage holidays

- src/app/manage/events/[id]/edit/page.jsx
- src/app/manage/events/[id]/page.jsx
- src/app/manage/events/new/page.jsx
- src/components/events/EventForm.jsx
- src/components/events/EventSponsor.jsx
- src/components/events/EventsFilter.jsx
- src/components/events/EventsGrid.jsx
- src/components/members/MembersFilter.jsx
- src/gql/queries/events.jsx
- EventForm: add a new entry for sponsor table
- Mange Event: view the sponsor table that was created
- https://github.com/Clubs-Council-IIITH/events/pull/71
> SponsorTable: add a sponsor table like budget table

- src/components/events/EventBudget.jsx
- src/components/events/EventForm.jsx
- src/components/events/EventSponsor.jsx
- src/components/events/EventsTable.jsx
- src/components/events/report/EventDocxDownloads.jsx
- src/components/events/report/EventReportDetails.jsx
- src/components/events/report/EventpdfDownloads.jsx
- src/gql/queries/events.jsx
- Change sponsor icon color in EventTable
- Add sponsor table to event report page
- Add sponsor table to event report pdf
- Add sponsor table to event report docx
> Add sponsor color icon add sponsors in event report

- src/app/changelog/page.jsx
- src/app/clubs-council/page.jsx
- src/app/manage/events/[id]/approve_cc/page.jsx
- src/app/tech-team/all-members/page.jsx
- src/app/tech-team/page.jsx
- src/components/clubs/ClubForm.jsx
- Change all the members calls from clubs to club.
- Whenever user.role is checked "cc" exists, otherwise cid and uid stuff have "clubs" for checking.
- https://github.com/Clubs-Council-IIITH/events/pull/82
- https://github.com/Clubs-Council-IIITH/members/pull/22
- Change cid in clubs collection, from "cc" to "clubs"
- Change all events cid's in event collection from "cc" to "clubs'
- Change all members cid's in members collection from "cc" to "clubs"
> change clubs cid from 'cc' to 'clubs'
